### PR TITLE
[PBW-4106]

### PR DESCRIPTION
**Pull request by aeng7**
IMA:
-Fixed an issue where overlay would get cancelled preemptively

### CODE REVIEW

**Comment by gfrankOoyala** [comment]
Not enough code changes, denied. Just kidding. Love 1 line code fixes. So easy to CR. LGTM but how about a unit test

**Comment by aeng7** [comment]
Will modify a current one.

**Comment by aeng7** [comment]
Unit test in.

**Comment by gfrankOoyala** [comment]
lgtm

**Pull request merged**
