### PR TITLE
Vpaid ad manager

### PR DESCRIPTION
**Pull request by nevermind89x**
Please review. Missing unit tests.

### CODE REVIEW

**Comment by nevermind89x** [comment]
Oh, you can't add comments on it, because its too long right? :no_mouth:

**Comment by dchauOoyala** [comment]
Diff is too large :disappointed:

**Comment by gfrankOoyala** [comment]
Impressive :), umm how can we do this.

**Comment by dchauOoyala** [comment]
maybe split the file into two commits and have them merged together?

**Comment by dchauOoyala** [comment]
two PRs **

**Pull request merged**
