### PR TITLE
[PLAYER-3539] Rename Ooyala Player SSAI plugin

### PR DESCRIPTION
**Pull request by ipadilla4**
https://jira.corp.ooyala.com/browse/PLAYER-3539

### CODE REVIEW

**Comment by dallen42** [comment]
@ipadilla4 we also need to update the unit test file ssai_pulse_test.js with the new names

**Comment by dallen42** [comment]
@ipadilla4 also, I think it would be a good idea to create a sandbox with this code and test to make sure that the renamed plugin will load in a debug page and work correctly

**Comment by ipadilla4** [comment]
Ok I will create a sandbox for this and let you know my findings.

**Comment by ipadilla4** [comment]
I tested the changes and it seems to be working fine. Debug page is here: http://tiny.cc/2577ty

**Comment by dallen42** [comment]
LGTM

**Comment by ipadilla4** [comment]
@cacel  I searched for files using SSAI plugin and the only one referencing it is the test file, which I already included in this PR.

**Pull request merged**
